
variables = {
    'comparison_variables': {
        'MEDHINC_CY': 'Median Household Income',
        'MEDVAL_CY':'Median Home Value',
        'AVGVAL_CY':'Average Home Value',
        'UNEMPRT_CY': 'Unemployment Rate',
        'CRMCYMURD': 'Murder Index',
        'CRMCYRAPE': 'Rape Index',
        'CRMCYROBB': 'Robbery Index',
        'CRMCYASST': 'Assault Index'
    },
    'noncomparison_variables':{
        'TOTHH_CY':'Total Households',
        'HINC0_CY_P':'Household Income: Less than $15,000',
        'HINC15_CY_P':'Household Income: $15,000-$24,999',
        'HINC25_CY_P':'Household Income: $25,000-$34,999',
        'HINC35_CY_P':'Household Income: $35,000-$49,999',
        'HINC50_CY_P':'Household Income: $50,000-$74,999',
        'HINC75_CY_P':'Household Income: $75,000-$99,999',
        'HINC100_CY_P':'Household Income: $100,000-$149,999',
        'HINC150_CY_P':'Household Income: $150,000-$199,999',
        'HINC200_CY_P':'Household Income: $200,000+',
        'AVGHHSZ_CY':'Average Household Size',
        'OWNER_CY':'Owner Occupied HUs',
        'RENTER_CY':'Renter Occupied HUs',
        'VACANT_CY':'Vacant Housing Units',
        'INCMORT_CY':'Percent of Income for Mortgage',
        'TSPOP10_CY':'2010 Total Population',
        'TSPOP11_CY':'2011 Total Population',
        'TSPOP12_CY':'2012 Total Population',
        'TSPOP13_CY':'2013 Total Population',
        'TSPOP14_CY':'2014 Total Population',
        'TSPOP15_CY':'2015 Total Population',
        'TSPOP16_CY':'2016 Total Population',
        'TSPOP17_CY':'2017 Total Population',
        'TSPOP18_CY':'2018 Total Population',
        'TSPOP19_CY':'2019 Total Population',
        'TOTPOP_CY':'2020 Total Population',
        'TSHU10_CY':'2010 Total Housing Units',
        'TSHU11_CY':'2011 Total Housing Units',
        'TSHU12_CY':'2012 Total Housing Units',
        'TSHU13_CY':'2013 Total Housing Units',
        'TSHU14_CY':'2014 Total Housing Units',
        'TSHU15_CY':'2015 Total Housing Units',
        'TSHU16_CY':'2016 Total Housing Units',
        'TSHU17_CY':'2017 Total Housing Units',
        'TSHU18_CY':'2018 Total Housing Units',
        'TSHU19_CY':'2019 Total Housing Units',
        'TOTHU_CY':'2020 Total Housing Units',
        'X3007_I':'Property Tax Index',
        'X3008_I':'Homeowner Insurance Index',
        'HSGRAD_CY_P':'High School Diploma',
        'SMCOLL_CY_P':'Some College/No Degree',
        'ASSCDEG_CY_P':'Associate''s Degree',
        'BACHDEG_CY_P':'Bachelor''s Degree',
        'GRADDEG_CY_P':'Graduate Degree',
        'INDAGRI_CY_P':'Emp Ind: Agriculture/Forestry/Fishing/Hunting',
        'INDMIN_CY_P':'Emp Ind: Mining/Quarrying/Oil & Gas Extraction',
        'INDCONS_CY_P':'Emp Ind: Construction',
        'INDMANU_CY_P':'Emp Ind: Manufacturing',
        'INDWHTR_CY_P':'Emp Ind: Wholesale Trade',
        'INDRTTR_CY_P':'Emp Ind: Retail Trade',
        'INDTRAN_CY_P':'Emp Ind: Transportation/Warehousing',
        'INDUTIL_CY_P':'Emp Ind: Utilities',
        'INDINFO_CY_P':'Emp Ind: Information (non-tech)',
        'INDFIN_CY_P':'Emp Ind: Finance/Insurance',
        'INDRE_CY_P':'Emp Ind: Real Estate/Rental/Leasing',
        'INDTECH_CY_P':'Emp Ind: Professional/Scientific/Technology',
        'INDMGMT_CY_P':'Emp Ind: Management of Companies/Enterprises',
        'INDADMN_CY_P':'Emp Ind: Admin/Support/Waste Management Services',
        'INDEDUC_CY_P':'Emp Ind: Educational Services',
        'INDHLTH_CY_P':'Emp Ind: Health Care/Social Assistance',
        'INDARTS_CY_P':'Emp Ind: Arts/Entertainment/Recreation',
        'INDFOOD_CY_P':'Emp Ind: Accommodation/Food Services',
        'INDOTSV_CY_P':'Emp Ind: Other Services',
        'INDPUBL_CY_P':'Emp Ind: Public Administration'
        },
    'employment_industry_variables':{

        'INDAGRI_CY_P': 'Emp Ind: Agriculture/Forestry/Fishing/Hunting',
        'INDMIN_CY_P': 'Emp Ind: Mining/Quarrying/Oil & Gas Extraction',
        'INDCONS_CY_P': 'Emp Ind: Construction',
        'INDMANU_CY_P': 'Emp Ind: Manufacturing',
        'INDWHTR_CY_P': 'Emp Ind: Wholesale Trade',
        'INDRTTR_CY_P': 'Emp Ind: Retail Trade',
        'INDTRAN_CY_P': 'Emp Ind: Transportation/Warehousing',
        'INDUTIL_CY_P': 'Emp Ind: Utilities',
        'INDINFO_CY_P': 'Emp Ind: Information (non-tech)',
        'INDFIN_CY_P': 'Emp Ind: Finance/Insurance',
        'INDRE_CY_P': 'Emp Ind: Real Estate/Rental/Leasing',
        'INDTECH_CY_P': 'Emp Ind: Professional/Scientific/Technology',
        'INDMGMT_CY_P': 'Emp Ind: Management of Companies/Enterprises',
        'INDADMN_CY_P': 'Emp Ind: Admin/Support/Waste Management Services',
        'INDEDUC_CY_P': 'Emp Ind: Educational Services',
        'INDHLTH_CY_P': 'Emp Ind: Health Care/Social Assistance',
        'INDARTS_CY_P': 'Emp Ind: Arts/Entertainment/Recreation',
        'INDFOOD_CY_P': 'Emp Ind: Accommodation/Food Services',
        'INDOTSV_CY_P': 'Emp Ind: Other Services',
        'INDPUBL_CY_P': 'Emp Ind: Public Administration'
    }
}